#ifndef mdb_commands_h
#define mdb_commands_h

#define MDB_FREERAM	(99)

#define MDB_CMD_OFFSET 100

// MDB commands for parse
#define MDB_CMD_RESET				(MDB_CMD_OFFSET + 0),1
#define MDB_CMD_VALIDATOR_STATUS	(MDB_CMD_OFFSET + 1)
#define MDB_CMD_CHANGER_STATUS		(MDB_CMD_OFFSET + 2)
#define MDB_CMD_BILL_TYPES			(MDB_CMD_OFFSET + 3)
#define MDB_CMD_ENABLE				(MDB_CMD_OFFSET + 4),1
#define MDB_CMD_DISABLE				(MDB_CMD_OFFSET + 5),1
#define MDB_CMD_ESCROW				(MDB_CMD_OFFSET + 6)
#define MDB_CMD_DISPENSE			(MDB_CMD_OFFSET + 7),1
#define MDB_CMD_TUBE_STATUS			(MDB_CMD_OFFSET + 8)
#define MDB_CMD_PAYOUT				(MDB_CMD_OFFSET + 9),1

#define MDB_CMD_NOPOLL				(MDB_CMD_OFFSET + 10),1

#define MDB_CMD_COIN_TYPES			(MDB_CMD_OFFSET + 11)

// ANSWERS
#define MDB_ANS_VALIDATOR_STATUS			(MDB_CMD_OFFSET + 20),6
#define MDB_ANS_VALIDATOR_BILL_TYPES		(MDB_CMD_OFFSET + 21),6
#define MDB_ANS_VALIDATOR_BILL_IN_ESCROW	(MDB_CMD_OFFSET + 22),1
#define MDB_ANS_VALIDATOR_BILL_ESCROW		(MDB_CMD_OFFSET + 23),1

#define MDB_ANS_CHANGER_STATUS				(MDB_CMD_OFFSET + 40),4
#define MDB_ANS_CHANGER_COIN_TYPES			(MDB_CMD_OFFSET + 41),6
#define MDB_ANS_CHANGER_COIN_ACCEPTED		(MDB_CMD_OFFSET + 42),1
#define MDB_ANS_CHANGER_COIN_DISPENSED		(MDB_CMD_OFFSET + 43),1
#define MDB_ANS_CHANGER_TUBE_STATUS			(MDB_CMD_OFFSET + 44),8
#define MDB_ANS_CHANGER_PAYOUT				(MDB_CMD_OFFSET + 45),1

#define MDB_ANS_CASHLESS_STATUS				(MDB_CMD_OFFSET + 60),6

#define MDB_ANS_DEBUG_VALIDATOR			(201),1
#define MDB_ANS_DEBUG_CHANGER			(202),1
#define MDB_ANS_FREERAM					(203),1
#define MDB_CMD_STACK					(MDB_CMD_OFFSET + 12) // ##112*
#define MDB_ANS_VALIDATOR_BILL_STACKED	(MDB_CMD_OFFSET + 24),1

#endif